<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Framework Quickstart Application</title>
    <?php
        echo $this->headLink()->appendStylesheet($this->baseUrl('media/css/global.css'));
        echo $this->headLink()->appendStylesheet($this->baseUrl('media/css/bootstrap.min.css'));
        echo $this->headLink()->appendStylesheet($this->baseUrl('media/css/bootstrap-theme.min.css'));
        echo $this->headScript()->prependFile( "media/js/jquery.min.js", $type = 'text/javascript' );
        echo $this->headScript()->prependFile( "media/js/bootstrap.min.js", $type = 'text/javascript' );
    ?>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li><a href="<?php echo $this->url(array('controller'=>'index'),'default',true) ?>">Home</a></li>
            <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'register'),'default',true) ?>">Register</a></li>
            <li><a href="<?php print $this->url(array('controller'=>'index', 'action' => 'sendmessage'),'default', true); ?>">Send message</a></li>
        </ul>

    </div><!-- /.navbar-collapse -->
</nav>

<?php echo $this->layout()->content ?>

</body>
</html>